const el=id=>document.getElementById(id); let content=null,chapters=[],current=0,pinned=-1,full=false,query='',hoverEnabled=true,scrollMode=false;
function splitSentences(text){const a=text.match(/[^。！？；]+[。！？；]?[」』]?/g)||[text];return a.map(s=>s.trim()).filter(Boolean)}
function splitTranslation(text,minParts){const parts=splitSentences(text);while(parts.length<minParts){let best=-1,cut=-1,score=Infinity;parts.forEach((part,i)=>{for(let p=0;p<part.length;p++)if('，、：'.includes(part[p])){const distance=Math.abs(p-part.length/2);if(part.length>18&&distance<score){best=i;cut=p;score=distance}}});if(best<0)break;const part=parts[best];parts.splice(best,1,part.slice(0,cut+1),part.slice(cut+1))}return parts}
function mapping(ch){if(ch.segments?.length)return ch.segments;const os=splitSentences(ch.original),ts=splitTranslation(ch.translation,os.length);const rows=os.map((s,i)=>{let a=Math.floor(i*ts.length/os.length),b=Math.floor((i+1)*ts.length/os.length);if(b<=a)b=a+1;return{original:s,translation:ts.slice(a,Math.min(b,ts.length)).join('')}});return rows.reduce((groups,row)=>{const last=groups[groups.length-1];if(last&&last.translation===row.translation)last.original+=row.original;else groups.push({...row});return groups},[])}
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function hi(s){const shown=(window.displayChinese||String)(s);if(!query)return esc(shown);return esc(shown).split(esc(query)).join('<mark>'+esc(query)+'</mark>')}
function renderNav(){el('nav').querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i===current))}
function markedTranslation(text,part){const at=text.indexOf(part);if(at<0)return esc(text);return esc(text.slice(0,at))+'<mark>'+esc(part)+'</mark>'+esc(text.slice(at+part.length))}
function show(i){const ch=chapters[current],map=mapping(ch),m=map[i];el('panelTitle').textContent=ch.title;el('quote').textContent=m.original;el('translation').className='translation';el('translation').innerHTML=full?markedTranslation(ch.translation,m.translation):esc(m.translation);el('fullToggle').hidden=false;el('fullToggle').textContent=full?'返回句子對照 ↑':`顯示本${content.sectionUnit}完整白話文 ↓`;document.querySelectorAll('.sentence').forEach((x,j)=>x.classList.toggle('active',j===i))}
function tooltip(s,i,event){if(!document.body.classList.contains('explanation-collapsed'))return;const m=mapping(chapters[i])[+s.dataset.i];el('hoverCard').innerHTML='<strong>'+esc(chapters[i].title)+'</strong>'+esc(m.translation);const x=Math.min(event.clientX+18,innerWidth-el('hoverCard').offsetWidth-20),y=Math.min(event.clientY+18,innerHeight-230);el('hoverCard').style.left=Math.max(12,x)+'px';el('hoverCard').style.top=Math.max(74,y)+'px';el('hoverCard').classList.add('visible')}
function hideTooltip(){el('hoverCard').classList.remove('visible')}
function bindSentences(scope=document,i=current){scope.querySelectorAll('.sentence').forEach(s=>{const n=+s.dataset.i;s.addEventListener('mouseenter',e=>{if(i===current&&pinned<0)show(n);if(hoverEnabled)tooltip(s,i,e)});s.addEventListener('mousemove',e=>{if(hoverEnabled&&document.body.classList.contains('explanation-collapsed'))tooltip(s,i,e)});s.addEventListener('mouseleave',()=>{if(hoverEnabled)hideTooltip()});s.addEventListener('focus',()=>{if(i===current&&pinned<0)show(n)});s.addEventListener('click',e=>{if(document.body.classList.contains('explanation-collapsed')){if(!hoverEnabled){el('hoverCard').classList.contains('visible')?hideTooltip():tooltip(s,i,e)}else{pinned=pinned===n?-1:n;tooltip(s,i,e)}return}pinned=pinned===n?-1:n;show(n)})})}
function label(i){return '第 '+String(i+1).padStart(2,'0')+' / '+String(chapters.length).padStart(2,'0')+' '+content.sectionUnit}
function render(){const ch=chapters[current],map=mapping(ch);el('count').textContent=label(current);el('title').innerHTML=hi(ch.title);el('sutra').innerHTML=map.map((m,i)=>'<span class="sentence" tabindex="0" data-i="'+i+'">'+hi(m.original)+'</span>').join('');pinned=-1;hideTooltip();el('panelTitle').textContent=ch.title;el('quote').textContent='';el('translation').className=full?'translation':'translation empty';el('translation').textContent=full?ch.translation:'將游標移到任一句經文，即可在此查看相應的白話解說。';el('fullToggle').hidden=!full;el('fullToggle').textContent=full?'返回句子對照 ↑':`顯示本${content.sectionUnit}完整白話文 ↓`;el('prevChapter').disabled=current===0;el('nextChapter').disabled=current===chapters.length-1;renderNav();bindSentences();if(!scrollMode)window.scrollTo({top:0,behavior:'smooth'})}
function go(i){current=Math.max(0,Math.min(chapters.length-1,i));query='';el('search').value='';if(scrollMode){document.getElementById('section-'+current).scrollIntoView({behavior:'smooth'});renderNav()}else render();el('nav').classList.remove('open')}
function renderScroll(){el('scrollReader').innerHTML=chapters.map((ch,ci)=>'<section class="scroll-section" id="section-'+ci+'"><div class="eyebrow">'+label(ci)+'</div><h2>'+hi(ch.title)+'</h2><div class="sutra">'+mapping(ch).map((m,i)=>'<span class="sentence" tabindex="0" data-i="'+i+'">'+hi(m.original)+'</span>').join('')+'</div><div class="scroll-translation">'+hi(ch.translation)+'</div></section>').join('');chapters.forEach((_,i)=>bindSentences(document.getElementById('section-'+i),i))}
function setView(scroll){scrollMode=scroll;document.body.classList.toggle('scroll-view',scroll);el('chapterView').setAttribute('aria-pressed',String(!scroll));el('scrollView').setAttribute('aria-pressed',String(scroll));if(scroll){renderScroll();setTimeout(()=>document.getElementById('section-'+current).scrollIntoView(),0)}else render()}
function initReader(){chapters.forEach((ch,i)=>{const b=document.createElement('button');b.dataset.chapter=i;b.textContent=ch.title;b.onclick=()=>go(i);el('nav').appendChild(b)});
el('menu').onclick=()=>el('nav').classList.toggle('open');
el('fullToggle').onclick=()=>{full=!full;localStorage.setItem(content.id+'-full-translation',String(full));show(pinned>=0?pinned:0)};
el('prevChapter').onclick=()=>go(current-1);el('nextChapter').onclick=()=>go(current+1);
el('navToggle').onclick=()=>{const on=document.body.classList.toggle('nav-collapsed');el('navToggle').setAttribute('aria-pressed',String(on));el('navToggle').textContent=on?'顯示目錄':'隱藏目錄'};
el('panelToggle').onclick=()=>{const on=document.body.classList.toggle('explanation-collapsed');el('panelToggle').setAttribute('aria-pressed',String(on));el('panelToggle').textContent=on?'顯示白話':'隱藏白話';hideTooltip()};
el('hoverMode').onclick=()=>{hoverEnabled=!hoverEnabled;el('hoverMode').setAttribute('aria-pressed',String(hoverEnabled));el('hoverMode').textContent=hoverEnabled?'懸停模式':'點擊模式';hideTooltip()};
el('chapterView').onclick=()=>setView(false);el('scrollView').onclick=()=>setView(true);
el('search').addEventListener('input',e=>{query=e.target.value.trim();if(!query){scrollMode?renderScroll():render();return}const shown=text=>(window.displayChinese||String)(text);const idx=chapters.findIndex(ch=>shown(ch.title).includes(query)||shown(ch.original).includes(query)||shown(ch.translation).includes(query));if(idx>=0){current=idx;scrollMode?renderScroll():render();if(scrollMode)setTimeout(()=>document.getElementById('section-'+current).scrollIntoView({behavior:'smooth'}),0)}});
addEventListener('keydown',e=>{if(e.target.matches('input,textarea'))return;if(e.key==='ArrowLeft')go(current-1);if(e.key==='ArrowRight')go(current+1);if(e.key.toLowerCase()==='m')el('navToggle').click();if(e.key.toLowerCase()==='e')el('panelToggle').click();if(e.key.toLowerCase()==='v')setView(!scrollMode);if(e.key==='Escape')hideTooltip()});
addEventListener('scroll',()=>{const d=document.documentElement;el('progress').style.width=(d.scrollTop/(d.scrollHeight-d.clientHeight)*100||0)+'%'});
render()}
async function start(){const response=await fetch(document.body.dataset.sutra);if(!response.ok)throw new Error('Content failed to load');content=await response.json();chapters=content.sections;full=localStorage.getItem(content.id+'-full-translation')==='true';document.title=content.title+'｜原文・白話互動閱讀';el('brandTitle').textContent=content.title;el('brandSubtitle').textContent=content.subtitle;el('navTitle').textContent=content.navTitle;initReader()}
start().catch(error=>{el('sutra').textContent='內容載入失敗，請重新整理頁面。';console.error(error)});
